name: Cron
on:
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 9AM US Eastern

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: python3.8 -m pip install nox
      - name: Build and upload package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: bash .ci/cron.sh

